name: goodreads-service
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: yarn install --ignore-optional --frozen-lockfile
    - run: yarn lint
    - run: yarn build
    - run: yarn test
